"""Agregando Una Columna

Revision ID: 2a19cdf8ca9c
Revises: 4e7ca4054db9
Create Date: 2022-11-20 12:40:12.666683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a19cdf8ca9c'
down_revision = '4e7ca4054db9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado2', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado2')
    # ### end Alembic commands ###
