"""Eliminando pais de Modelo Usuarios

Revision ID: 39196ef99397
Revises: 090dc43aa6b2
Create Date: 2022-11-20 12:50:14.652334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39196ef99397'
down_revision = '090dc43aa6b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'pais')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pais', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
