"""Eliminar Columna Estado2

Revision ID: ddf432cd1f7a
Revises: 2a19cdf8ca9c
Create Date: 2022-11-20 12:47:03.609329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf432cd1f7a'
down_revision = '2a19cdf8ca9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado2', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
